# Generated by Django 4.0.4 on 2022-04-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='phone',
            field=models.IntegerField(unique=True),
        ),
    ]
